### ISSUE TITLE
[PE-D][Tester B] The app does not allow two different people who may have the same name

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-4/tp#294]
Two completely different people who have the same name cannot be added to the app at the same time
I tried adding two buyers who have the same name but all other details as different.
I would imagine that it is a common situation where two people have the same names so this might be inconvenient to the user.

![buyer nAlex Yeoh p85555555 ereal@real.com.png](https://raw.githubusercontent.com/aditig0305/ped/main/files/d1a027b5-702b-4547-b407-c96790c2eeff.png)￼

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: aditig0305/ped#5

**Comment by seandias** [comment]
But you need a way to differentiate them right? Dont tell me you save 2 different contacts in the same way in your phone and somehow can magically identify them by their phone number.
