### ISSUE TITLE
[PE-D][Tester D] Specificity of error message for `buyer`

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F11-4/tp#301]
To recreate this, type `buyer n/John p/912345678`

This is the current error message:
![image.png](https://raw.githubusercontent.com/luileng/ped/main/files/560e47e3-9b83-4ffe-a007-880cd151e019.png)

In a case like this, the user may have to manually check which parameter they are missing from the command. While it’s not a major issue, it could cause some inconvenience. An improvement could be to detect missing prefixes and display a message indicating which ones are missing. This might make the experience smoother for users.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: luileng/ped#4

**Comment by seandias** [comment]
We show an example which is also very easy to read for users. So do read in the future. Thanks!
